//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.data.database.draw
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int index { get; set; }
        public string userid { get; set; }
        public string channal { get; set; }
        public string username { get; set; }
        public int SSR { get; set; }
        public int SR { get; set; }
        public int R { get; set; }
        public int totaldrawcount { get; set; }
    }
}
